### ISSUE TITLE
how to clear setting and reset back to system dialer app

### ISSUE THREAD

**Issue by shmehdi01** [arekolek/simple-phone#4]

**Comment by shmehdi01** [comment]
I want reset my app setting and go back to system dialer app? How it is possible?

**Comment by arekolek** [comment]
One option is to delete the phone app you don't want, the system will revert to default one.

Another is to find the "Default apps" settings in your phone system settings, which exact location vary depending on the manufacturer.

Like mentioned in the README, in stock Android that's: Settings -> Apps & notifications -> Advanced -> Default apps -> Phone app:

**Comment by shmehdi01** [comment]
I know but i want to reset programmatically, if i uninstall the app when ever i reinstall it automatically detect if previously used as default dialer.

**Comment by arekolek** [comment]
The best you can do is to use an intent with [ACTION_MANAGE_DEFAULT_APPS_SETTINGS](https://developer.android.com/reference/android/provider/Settings#ACTION_MANAGE_DEFAULT_APPS_SETTINGS)

Maybe, you could also [find out what the system dialer is by doing what Android does](https://android.googlesource.com/platform/frameworks/base/+/master/telecomm/java/android/telecom/DefaultDialerManager.java#144) and then pass that package name instead of yours to the 

```
Intent(ACTION_CHANGE_DEFAULT_DIALER)
    .putExtra(EXTRA_CHANGE_DEFAULT_DIALER_PACKAGE_NAME, packageName)
```

and I wouldn't expect anything more automated than that, because it would be weird if an app could change the dialer without asking the user about it.
